export { initDb, initTestDb, getDb, closeDb } from './connection.js';
export { runMigrations } from './migrations/index.js';
export { markInboundSeen, pruneInboundDedup } from './inbound-dedup.js';
export {
  archiveConversationLane,
  createConversationBinding,
  createConversationLane,
  createConversationLaneRootSession,
  findActiveConversationBinding,
  getConversationBinding,
  getConversationLane,
  linkLegacyFeishuSession,
  linkSessionToConversationLane,
  listConversationBindings,
  listConversationLanesForUser,
  revokeConversationBinding,
  sessionForConversationLane,
  ConversationBindingConflictError,
  ConversationLaneConflictError,
  type AnySessionMode,
  type UserScopedSessionMode,
} from './conversation-lanes.js';
export {
  authenticateWebSession,
  consumeWebAuthTransaction,
  createWebAuthSession,
  createWebAuthTransaction,
  getWebAuthSessionByHash,
  purgeExpiredWebAuthTransactions,
  revokeAllWebAuthSessionsForUser,
  revokeWebAuthSessionByToken,
  rotateWebAuthSession,
  verifyWebCsrf,
  WebAuthStateError,
  type AuthenticatedWebSession,
  type WebAuthSessionPolicy,
  type WebAuthStateErrorReason,
} from './web-auth.js';
export {
  completeWebMessageReceipt,
  getWebMessageReceipt,
  messageBaseIdFromReceipt,
  reserveWebMessageReceipt,
  type WebMessageReceipt,
  type WebMessageReceiptStatus,
} from './web-message-receipts.js';
export {
  appendWebEvent,
  clearWebEventSubscribersForTests,
  decodeWebEventCursor,
  encodeWebEventCursor,
  listWebEventsAfter,
  subscribeWebEvents,
  type WebEvent,
  type WebEventCursor,
  type WebEventType,
} from './web-events.js';
export {
  backfillLegacyFeishuOpenIds,
  createUserIdentity,
  getUserIdentitiesForUser,
  getUserIdentity,
  getUserIdentityById,
  relinkUserIdentity,
  resolveOrCreateCanonicalUser,
  touchUserIdentity,
  UserIdentityConflictError,
  type CreateUserIdentityInput,
  type ResolveUserIdentityInput,
  type UserIdentityKey,
} from './user-identities.js';
export { listSessions, traceRequest, type SessionFilter, type RequestTrace } from './operator-queries.js';
export {
  createAgentGroup,
  getAgentGroup,
  getAgentGroupByFolder,
  getAllAgentGroups,
  updateAgentGroup,
  deleteAgentGroup,
} from './agent-groups.js';
export {
  createMessagingGroup,
  getMessagingGroup,
  getMessagingGroupByPlatform,
  getAllMessagingGroups,
  getMessagingGroupsByChannel,
  updateMessagingGroup,
  deleteMessagingGroup,
  createMessagingGroupAgent,
  getMessagingGroupAgents,
  getMessagingGroupAgent,
  getMessagingGroupAgentByPair,
  updateMessagingGroupAgent,
  deleteMessagingGroupAgent,
} from './messaging-groups.js';
export {
  createSession,
  getSession,
  findSession,
  findSessionForAgentOwner,
  findSessionForAgentRoot,
  findActiveSessionForConversationLane,
  findSessionByAgentGroup,
  getSessionsByAgentGroup,
  getActiveSessions,
  getRunningSessions,
  findArchivableSessions,
  findArchivedSessionsOlderThan,
  countSessionsByStatus,
  updateSession,
  deleteSession,
  createPendingQuestion,
  getPendingQuestion,
  deletePendingQuestion,
  createPendingApproval,
  getPendingApproval,
  updatePendingApprovalStatus,
  deletePendingApproval,
  getPendingApprovalsByAction,
} from './sessions.js';
